# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:

    docker:
      - image: paulvitic/peof-circleci:20190803185216
        docker_layer_caching: true

      - image: circleci/mongo:4
        environment:
          ENV MONGO_INITDB_ROOT_USERNAME: root
          ENV MONGO_INITDB_ROOT_PASSWORD: password
          ENV MONGO_INITDB_DATABASE: admin

      - image: rabbitmq:3
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
          RABBITMQ_DEFAULT_VHOST: /

    steps:
      - checkout

      - run:
          name: Wait for RabbitMQ
          command: wait-for-container RabbitMQ localhost 5672 20

      - run:
          name: Wait for MongoDB
          command: wait-for-container MongoDB localhost 27017 20

      - run:
          name: Initialize MongoDB
          command: |
            mongo localhost:27017 < /home/circleci/mongo/mongo-init.js

      # static code analysis & coverage
      - run:
          name: Static code analysis on organization-ui
          command: |
            pwd
            eslint organization-ui/src

      - run:
          name: Copy organization source into GOPATH src directory and pull all dependencies
          command: |
            cp -r organization/src/organization.peof /go/src/organization.peof
            cd /go/src/organization.peof
            go get -v -t -d ./...

      - run:
          name: Execute tests
          environment:
            PROFILE: "ci"
          command: |
            go test -v ./...