AWSTemplateFormatVersion: '2010-09-09'
Description: 'PEOF users, groups and policies'
Parameters:
  PEOFContainerRepositoriesRootArn:
    Type: String
    Description: Root ARN of the container repositories of peof project
#  Password:
#    NoEcho: 'true'
#    Type: String
#    Description: New account password
#    MinLength: '1'
#    MaxLength: '41'
#    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  PEOFCircleCIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: peof-circleci-user
#    Properties:
#      LoginProfile:
#        Password: !Ref 'Password'
  PEOFCircleCIGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: peof-circleci-users
  PEOFCircleCIUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'PEOFCircleCIGroup'
      Users: [!Ref 'PEOFCircleCIUser']
  PEOFCircleCIPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECRAccessPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: ['ecr:GetAuthorizationToken']
            Resource: '*'
          - Effect: Allow
            Action: ['ecr:GetDownloadUrlForLayer','ecr:BatchGetImage','ecr:BatchCheckLayerAvailability','ecr:PutImage','ecr:InitiateLayerUpload','ecr:UploadLayerPart','ecr:CompleteLayerUpload']
            Resource:
              - !Ref 'PEOFContainerRepositoriesRootArn'
      Groups: [!Ref 'PEOFCircleCIGroup']
  PEOFCircleCIUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'PEOFCircleCIUser'
Outputs:
  AccessKey:
    Value: !Ref 'PEOFCircleCIUserKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [PEOFCircleCIUserKey, SecretAccessKey]
    Description: AWSSecretAccessKey of new user