AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PEOFRepositoryName:
    Type: String
Resources:
  ContainerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref PEOFRepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Only keep 8 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 8
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
Outputs:
  Arn:
    Value: !GetAtt ContainerRepo.Arn