AWSTemplateFormatVersion: '2010-09-09'
Description: "a bucket and an IAM user and lock the bucket down to be accessible by that new user."
Resources:
  PEOFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: peof-bucket
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
          - NoncurrentVersionExpirationInDays: 1
            Status: Enabled
  PEOFBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PEOFBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${PEOFBucket.Arn}/*'
Outputs:
  BucketName:
    Description: 'Name of the bucket'
    Value: !Ref PEOFBucket
  BucketArn:
    Description: 'Bucket ARN'
    Value: !GetAtt 'PEOFBucket.Arn'
  BucketDomainName:
    Description: 'Domain name of the bucket.'
    Value: !GetAtt 'PEOFBucket.DomainName'